AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Common:
    Type: String
  
Resources:
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-task-execution-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Common
          Value: !Ref Common

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: codedeploy-service-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS
      Tags:
        - Key: Common
          Value: !Ref Common
Outputs:
  EcsTaskExecutionRole:
    Value: !GetAtt EcsTaskExecutionRole.Arn
  CodeDeployRole:
    Value: !GetAtt CodeDeployRole.Arn